#Database setting
spring.datasource.url=jdbc:mysql://localhost:3306/yourDBName?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=
spring.datasource.password=

#JPA/Hibernate setting
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#Public Data API key (Open API Key)
api.service-key=?

#jwt key
jwt.secret=v9y$B&E)H@McQfTjWnZr4u7x!A%C*F-JaNdRgUkXp2s5v8y/B?E(G+KbPeShVmYq
#24hour
jwt.expiration=86400000